"""add final recruiter decision

Revision ID: 2ece38bfa02e
Revises: cea83ca833fb
Create Date: 2026-09-18 18:39:54.607887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ece38bfa02e'
down_revision: Union[str, Sequence[str], None] = 'cea83ca833fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('final_decision', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('final_decision_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('final_decision_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'final_decision_at')
    op.drop_column('applications', 'final_decision_notes')
    op.drop_column('applications', 'final_decision')
    # ### end Alembic commands ###
