"""add schedule draft fields

Revision ID: cea83ca833fb
Revises: ccd278fc14f0
Create Date: 2026-09-17 00:25:03.037458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea83ca833fb'
down_revision: Union[str, Sequence[str], None] = 'ccd278fc14f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_schedules', sa.Column('event_title', sa.String(length=500), nullable=True))
    op.add_column('interview_schedules', sa.Column('event_description', sa.Text(), nullable=True))
    op.add_column('interview_schedules', sa.Column('candidate_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_schedules', 'candidate_message')
    op.drop_column('interview_schedules', 'event_description')
    op.drop_column('interview_schedules', 'event_title')
    # ### end Alembic commands ###
